trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build_Stage
  jobs:
    - job: Build_Job
      steps:
        - task: DotNetCoreCLI@2
          displayName: 'Restore'
          inputs:
            command: 'restore'
            projects: '*.csproj'
            feedsToUse: 'select'
        - task: DotNetCoreCLI@2
          displayName: 'Build'
          inputs:
            command: 'build'
            projects: '*.csproj'
            arguments: '--configuration Release'
        - task: DotNetCoreCLI@2
          displayName: 'Publish'
          inputs:
            command: 'publish'
            publishWebProjects: true
            arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)'
        - script: ls -R $(Build.ArtifactStagingDirectory)
          displayName: 'Verify Publish Output'
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: 'drop'
            publishLocation: 'Container'

- stage: Deploy_Dev
  jobs:
    - deployment: DeploymentApproval
      environment: Dev
    - job: Deploy_to_webapp
      steps:
        - task: DownloadBuildArtifacts@1
          inputs:
            buildType: 'current'
            downloadType: 'single'
            artifactName: 'drop'
            itemPattern: '**'
            downloadPath: '$(System.DefaultWorkingDirectory)'
        - script: ls -R $(System.DefaultWorkingDirectory)
          displayName: 'Verify Downloaded Artifacts'
        - task: AzureRmWebAppDeployment@4
          inputs:
            ConnectionType: 'AzureRM'
            azureSubscription: 'dotnet7_webapp'
            appType: 'webAppLinux'
            WebAppName: 'AzureTrainingwebapp'
            packageForLinux: '$(System.DefaultWorkingDirectory)/drop/**/*.zip'
            RuntimeStack: 'DOTNETCORE|7.0'
